name: make project CI

on: [push, pull_request]

jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: clone soapy-sdr
      run: git clone https://github.com/pothosware/SoapySDR.git
    - name: checkout version 0.7.1 of soapy-sdr
      run: cd SoapySDR && git checkout -b soapy-sdr-0.7.1    
    - name: cmake soapy-sdr
      run: cd SoapySDR && mkdir build && cd build && cmake ..
    - name: make soapy-sdr
      run: cd SoapySDR/build && make
    - name: install soapy-sdr
      run: cd SoapySDR/build && sudo make install

    - name: install liquid-dsp dependency
      run: sudo apt-get install automake autoconf
    - name: clone liquid-dsp 
      run: git clone git://github.com/jgaeddert/liquid-dsp.git
    - name: checkout version 1.3.2 of liquid-dsp 
      run: cd liquid-dsp && git checkout -b v1.3.2
    - name: bootstrap
      run: cd liquid-dsp && ./bootstrap.sh
    - name: configure
      run: cd liquid-dsp && ./configure     
    - name: make liquid-dsp
      run: cd liquid-dsp && make
    - name: install liquid-dsp
      run: cd liquid-dsp && sudo make install     
                                        
    - name: make dsp-projects
      run: make 
